# Kibana server settings
server.name: kibana
server.host: "0.0.0.0"
server.port: 5601

# Elasticsearch connection
elasticsearch.hosts: ["http://elasticsearch:9200"]
elasticsearch.username: elastic
elasticsearch.password: changeme

# Monitoring settings
monitoring.ui.container.elasticsearch.enabled: true
monitoring.ui.container.logstash.enabled: true

# Telemetry settings
telemetry.enabled: false

# Internationalization settings
i18n.locale: "en"

# Default settings
kibana.index: ".kibana"

# Security settings (disabled for development)
xpack.security.enabled: false
xpack.encryptedSavedObjects.encryptionKey: "something_at_least_32_characters"

# Reporting settings
xpack.reporting.enabled: false

# Canvas settings
xpack.canvas.enabled: true

# Graph settings
xpack.graph.enabled: true

# ML settings
xpack.ml.enabled: true

# Monitoring settings
xpack.monitoring.enabled: true